### PR TITLE
Test project Urvashi

### LINKED ISSUE #2: Add GitHubTeacher's Home Town Tips
## Fuquay Varina, NC
- Places to eat
- Fun things to do
- Things to avoid
### Task List
- [x] Create a branch
- [x] Add my file
- [x] Create a pull request
- [ ] Discuss
- [ ] Merge pull request

### PR DESCRIPTION
**Pull request by urvashinayak123**
Extended description would go here ! Closes #2

### CODE REVIEW

**Comment by schandra47** [comment]
@urvashinayak123 please correct the typo "xcdbvfbf" :smirk:

**Comment by urvashinayak123** [comment]
Ok will do :-)

**Comment by urvashinayak123** [comment]
@schandra47 ..Unable to update name :-1:

**Comment by niraj007** [comment]
go for it....

**Pull request merged**
