### PR TITLE
created my first file to be committed short descr

### LINKED ISSUE #8: Add cwarkulw Home Town Tips
## Anytown, NJ
- [x] Create a branch
- [x] Add my file
- [x]  Create a pull request
- [ ]  Discuss
- [ ]  Merge pull request

### PR DESCRIPTION
**Pull request by cwarkulw**
Here is my long description of the changes made to my first file Closes #8

### CODE REVIEW

**Comment by rparkin** [comment]
This looks good.

**Comment by cwarkulw** [comment]
My code changes are perfect, I swear, trust me.  They worked fine on my PC.  Please approve for merge.

**Comment by rparkin** [comment]
Approved.

**Comment by kishorebolinidi** [comment]
Hola.. :dart:

**Pull request merged**
