### PR TITLE
created new file git testing

### LINKED ISSUE #6: Add dhanashreewaghmare home town tips
## creating a issue

Task List
- [x] Create a branch
- [x] Add my file 
- [x] create a pull request
- [x] Discussion
- testing

### PR DESCRIPTION
**Pull request by dhanashreeW**
adding extended description Closes #6

### CODE REVIEW

**Comment by dhanashreeW** [comment]
testing comments

**Comment by schandra47** [comment]
@babipal :+1: good comment :smile:

**Comment by dhanashreeW** [comment]
@babipal this is going to break the whole site :-1:

**Comment by babipal** [comment]
Still no description on your hometown. -1

**Comment by babipal** [comment]
fine, :shipit:

**Pull request merged**
