### PR TITLE
Jyanda home town pull request 1

### LINKED ISSUE #18: Add jyanda Home Town Tips
## Maplewood, NJ
- [x] Create a branch
- [x] Add my life
- [x] Create pull request
- [ ] Discuss
- [ ] Merge pull request
- Good things to do
- Places to eat
- Watch out for these

### PR DESCRIPTION
**Pull request by jyanda**
Closes #18

### CODE REVIEW

**Comment by jyanda** [comment]
this is looking pretty good so far...

**Comment by brian-t-smith** [comment]
**Looks Good**

**Comment by jyanda** [comment]
# yeah, super great
- [ ] check this off...
- thanks

**Comment by brian-t-smith** [comment]
# big words

**Comment by babipal** [comment]
I also live in Maplewood. I like Arturos and St. James Gate.

**Comment by jyanda** [comment]
this looks good

**Pull request merged**
