### PR TITLE
created new file Maplewood NJ

### LINKED ISSUE #10: Add babipal's home town tips
Task List
- [x] Create a branch
- [x] Add my file 
- [x] create a pull request
- [] Discussion
- [] testing
### Restaurants
- Arturos (pizza)
- Able Baker (bakery)
### Bars
- St. James Gate
- Liberty Tavern
- O'Riely's

### PR DESCRIPTION
**Pull request by babipal**
first time commit. Closes #10

### CODE REVIEW

**Comment by billbbby** [comment]
Sounds good. Maybe I'll visit. Then again, maybe I won't

**Comment by babipal** [comment]
@dhanashreeW  - can you review and merge?

**Comment by babipal** [comment]
@billbbby - can you review?

**Comment by billbbby** [comment]
All's well

**Pull request merged**
