### PR TITLE
created new file for hometown.

### LINKED ISSUE #14: Add brian-t-smith home town tips
## Los Angeles, CA

**Checklist**
- [x] Create a branch
- [x] Add my file
- [x] Create a pull request
- [ ] Discuss
- [ ] Merge pull request

_Created by: Brian T Smith_

### PR DESCRIPTION
**Pull request by brian-t-smith**
extended description goes here.Closes #14

### CODE REVIEW

**Comment by amohile** [comment]
test

**Comment by jyanda** [comment]
# you've got it happening
- all good

**Comment by jyanda** [comment]
- [ ] check meister

**Comment by niraj007** [comment]
testing subscription

**Comment by jyanda** [comment]
Hey @stevegam take a look.

**Comment by brian-t-smith** [comment]
looks good :ship:

**Comment by schandra47** [comment]
I am not moving there ever :wink:

**Comment by brian-t-smith** [comment]
this looks good :shipit:

**Pull request merged**
