### PR TITLE
Stevegam home town

### LINKED ISSUE #24: Add stevegam Home Town Tips
## West Orange, NJ
- Places to eat
- Fun thing to do
- Things to avoid

### PR DESCRIPTION
**Pull request by stevegam**
Closes #24

### CODE REVIEW

**Comment by sobannithy** [comment]
Please suggest few good diners in your area

**Comment by stevegam** [comment]
This looks good it I have to say so myself

**Comment by sobannithy** [comment]
Looks good

**Comment by sobannithy** [comment]
Looks good, thanks for the info!

**Pull request merged**
